// Code generated by convToMap. DO NOT EDIT !!!

package unit_test

// Map2Struct converts a map[string]any to the Example struct.
func (src *Example) Map2Struct(mm map[string]any) {

	if mm["fooPtr"] != nil {
		tep := &Foo{}
		if mmm, ok := mm["fooPtr"].(map[string]any); ok {
			tep.Map2Struct(mmm)
		}
		src.FooPtr = tep
	}

	if val, ok := mm["foo"]; ok {
		tep := &Foo{}
		if mmm, ok := val.(map[string]any); ok {
			tep.Map2Struct(mmm)
		}
		src.Foo = *tep
	}

	if val, ok := mm["id"].(int); ok {
		src.ID = val
	}

	if val, ok := mm["name"].(string); ok {
		src.Name = val
	}

	if val, ok := mm["float64"].(float64); ok {
		src.Float = val
	}

	if mm["ptrInt"] != nil {
		if val, ok := mm["ptrInt"].(*int64); ok {
			src.PtrInt = val
		} else {
			if val, ok := mm["ptrInt"].(int64); ok {
				src.PtrInt = &val
			}
		}
	}

	if val, ok := mm["a"].(string); ok {
		src.A = val
	}

	if val, ok := mm["b"].(int); ok {
		src.B = val
	}

	if mm["foos"] != nil {
		if mmm, ok := mm["foos"].([]Foo); ok {
			src.Foos = mmm
		}
	}

}

// Map2Struct converts a map[string]any to the InlineStruct struct.
func (src *InlineStruct) Map2Struct(mm map[string]any) {

	if val, ok := mm["a"].(string); ok {
		src.A = val
	}

	if val, ok := mm["b"].(int); ok {
		src.B = val
	}

}

// Map2Struct converts a map[string]any to the Foo struct.
func (src *Foo) Map2Struct(mm map[string]any) {

	if val, ok := mm["bar"].(string); ok {
		src.Bar = val
	}

}
