// Code generated by convToMap. DO NOT EDIT.

package unit_test

// _2Map converts the Example struct to a map[string]any.
func (s *Example) _2Map() map[string]any {
	m := make(map[string]any)

	if s.FooPtr != nil {
		m["fooPtr"] = s.FooPtr._2Map()
	}

	m["foo"] = s.Foo._2Map()

	m["id"] = s.ID

	m["name"] = s.Name

	m["float64"] = s.Float

	m["A"] = s.A

	m["B"] = s.B

	return m
}

// _2Map converts the InlineStruct struct to a map[string]any.
func (s *InlineStruct) _2Map() map[string]any {
	m := make(map[string]any)

	m["A"] = s.A

	m["B"] = s.B

	return m
}

// _2Map converts the Foo struct to a map[string]any.
func (s *Foo) _2Map() map[string]any {
	m := make(map[string]any)

	m["bar"] = s.Bar

	return m
}
