// Code generated by convToMap. DO NOT EDIT !!!

package unit_test

// ToStringMap converts the Example struct to a map[string]any.
func (s *Example) ToStringMap() map[string]any {
	m := make(map[string]any)

	if s.FooPtr != nil {
		m["fooPtr"] = s.FooPtr.ToStringMap()
	}

	m["foo"] = s.Foo.ToStringMap()

	if s.ID != 0 {
		m["id"] = s.ID
	}

	if s.Name != "" {
		m["name"] = s.Name
	}

	if s.Float != 0 {
		m["float64"] = s.Float
	}

	if s.PtrInt != nil {
		m["ptrInt"] = s.PtrInt
	}

	if s.A != "" {
		m["a"] = s.A
	}

	if s.B != 0 {
		m["b"] = s.B
	}

	m["str2Foo"] = s.Str2Foo

	if len(s.Foos) > 0 {
		m["foos"] = s.Foos
	}

	return m
}

// ToStringMap converts the InlineStruct struct to a map[string]any.
func (s *InlineStruct) ToStringMap() map[string]any {
	m := make(map[string]any)

	if s.A != "" {
		m["a"] = s.A
	}

	if s.B != 0 {
		m["b"] = s.B
	}

	return m
}

// ToStringMap converts the Foo struct to a map[string]any.
func (s *Foo) ToStringMap() map[string]any {
	m := make(map[string]any)

	if s.Bar != "" {
		m["bar"] = s.Bar
	}

	return m
}
