// Code generated by convToMap. DO NOT EDIT !!!

package unit_test

// ToStringMap converts the SimpleExample struct to a map[string]any.
func (s *SimpleExample) ToStringMap() map[string]any {
	m := make(map[string]any)

	if s.Str != "" {
		m["str"] = s.Str
	}

	m["point"] = s.Point.ToStringMap()

	if s.K != nil {
		m["k"] = s.K
	}

	return m
}

// ToStringMap converts the Point struct to a map[string]any.
func (s *Point) ToStringMap() map[string]any {
	m := make(map[string]any)

	if s.X != 0 {
		m["x"] = s.X
	}

	if s.Y != 0 {
		m["y"] = s.Y
	}

	return m
}

// ToStringMap converts the NMIXX struct to a map[string]any.
func (s *NMIXX) ToStringMap() map[string]any {
	m := make(map[string]any)

	if s.K != nil {
		m["k"] = s.K
	}

	return m
}
