// Code generated by convToMap. DO NOT EDIT !!!

package unit_test

// Map2Struct converts a map[string]any to the SimpleExample struct.
func (src *SimpleExample) Map2Struct(mm map[string]any) {

	if val, ok := mm["str"].(string); ok {
		src.Str = val
	}

	if val, ok := mm["point"]; ok {
		tep := &Point{}
		if mmm, ok := val.(map[string]any); ok {
			tep.Map2Struct(mmm)
		}
		src.Point = *tep
	}

	if mm["k"] != nil {
		if val, ok := mm["k"].(*string); ok {
			src.K = val
		} else {
			if val, ok := mm["k"].(string); ok {
				src.K = &val
			}
		}
	}

}

// Map2Struct converts a map[string]any to the Point struct.
func (src *Point) Map2Struct(mm map[string]any) {

	if val, ok := mm["x"].(int); ok {
		src.X = val
	}

	if val, ok := mm["y"].(float64); ok {
		src.Y = val
	}

}

// Map2Struct converts a map[string]any to the NMIXX struct.
func (src *NMIXX) Map2Struct(mm map[string]any) {

	if mm["k"] != nil {
		if val, ok := mm["k"].(*string); ok {
			src.K = val
		} else {
			if val, ok := mm["k"].(string); ok {
				src.K = &val
			}
		}
	}

}
