package map_to_struct

import "github.com/nan-www/convToMap/generator"

const GenTemplate = `// Code generated by convToMap. DO NOT EDIT !!!

package {{.PackageName}}

{{range .Structs}}
// Map2Struct converts a map[string]any to the {{.Name}} struct.
func (src *{{.Name}}) Map2Struct(mm map[string]any){
    {{range .Fields}}
		{{if not .Type}}{{continue}}{{end}}
		{{if .IsMap}}
		if mm["{{.TagName}}"] != nil {
			if mmm, ok := mm["{{.TagName}}"].(map[{{.MapKey.Type}}]{{.MapValue.Type}}); ok {
				for k, v := range mmm {
					src.{{.Name}}[k] = v
				}
			}
		}
		{{else if .IsArray}}
		if mm["{{.TagName}}"] != nil {
            if mmm, ok := mm["{{.TagName}}"].([]{{.Type}}); ok {
				src.{{.Name}} = mmm
			}
		}
		{{else if .IsPtrObj}}
		if mm["{{.TagName}}"] != nil {
			tep := &{{.Type}}{}
            if mmm, ok := mm["{{.TagName}}"].(map[string]any); ok {
				tep.Map2Struct(mmm)
			}
			src.{{.Name}} = tep
		}
		{{else if .IsObj}}
         if val, ok := mm["{{.TagName}}"]; ok {
			tep := &{{.Type}}{}
			 if mmm, ok := val.(map[string]any); ok {
				tep.Map2Struct(mmm)
			}
			src.{{.Name}} = *tep
		}
		{{else if .IsPtr}}
		if mm["{{.TagName}}"] != nil {
			src.{{.Name}} = mm["{{.TagName}}"].({{.Type}})
		}
		{{else}}
		if mm["{{.TagName}}"] != nil {
			src.{{.Name}} = mm["{{.TagName}}"].({{.Type}})
		}
		{{end}}
    {{end}}
}
{{end}}
`

func GenStruct2MapFile(filename string) {
	// 设置要查找的特定 go:generate 标识
	generator.Gen(filename, "//go:generate convToMap", GenTemplate)
}
