package struct_to_map

import "github.com/nan-www/convToMap/generator"

const GenTemplate = `// Code generated by convToMap. DO NOT EDIT !!!

package {{.PackageName}}

{{range .Structs}}
// ToStringMap converts the {{.Name}} struct to a map[string]any.
func (s *{{.Name}}) ToStringMap() map[string]any {
    m := make(map[string]any)
    {{range .Fields}} 
		{{if .IsArray}}
		if len(s.{{.Name}}) > 0 {
			m["{{.TagName}}"] = s.{{.Name}}
		}
		{{else if .IsPtrObj}}
		if s.{{.Name}} != nil {
			m["{{.TagName}}"] = s.{{.Name}}.ToStringMap()
		}
		{{else if .IsObj}}
		m["{{.TagName}}"] = s.{{.Name}}.ToStringMap()
		{{else if .IsPtr}}
		if s.{{.Name}} != nil {
			m["{{.TagName}}"] = s.{{.Name}}
		}
		{{else}}
			{{if eq .Type "string"}}
			if s.{{.Name}} != "" {
				m["{{.TagName}}"] = s.{{.Name}}
			}
			{{else if or (eq .Type "int") (eq .Type "int32") (eq .Type "int64") (eq .Type "float64") (eq .Type "float32")}}
			if s.{{.Name}} != 0 {
				m["{{.TagName}}"] = s.{{.Name}}
			}
			{{else}}
			m["{{.TagName}}"] = s.{{.Name}}
			{{end}}
		{{end}}
    {{end}} 

    return m 
}
{{end}}
`

func GenStruct2MapFile(filename string) {
	// 设置要查找的特定 go:generate 标识
	generator.Gen(filename, "//go:generate convToMap", GenTemplate)
}
